#!/bin/bash

VERSION=0.0.8

##########################################################################################
#                                                                                        #
# 4Toolz Collection 0.0.8 (4Toolz)                                                       #
#                                                                                        #
# Idea / Written by Sebastian Vivian Gresser - All Rights Reserved                       #
#                                                                                        #
# Copyright (C) by geeBee UG (haftungsbeschränkt) - All Rights Reserved                  #
# Copyright (C) by Sebastian Vivian Gresser - All Rights Reserved                        #
#                                                                                        #
##########################################################################################
#                                                                                        #
# WARRANTY AND RESPONSIBILITY: there is no warranty you are responsible on your own      #
#                              how you are using this tool set.                          #
#                                                                                        #
##########################################################################################
#                                                                                        #
#                                       CONTENTS:                                        #
#                                                                                        #
##########################################################################################
#                                                                                        #
########################################## 4NET ##########################################
#                                                                                        #
# <->4utoBl4ck: will blackhole any suspicious ips or domains in the domainlist           #
#  |-> 4utoBl4ck needs Grsecurity's blackhole patch for ip route to work properly!!!     #
#  with cron you can add this to auto-blackhole any network if you have their            #
#  load balance domain names                                                             #
#                                                                                        #
###################################### 4MAINTENANCE ######################################
#                                                                                        #
# <->4git: will start multiple based git pull or clone processes                         #
#  |->                                                                                   #
#  with cron you can add this to update your git repo collection regularly               #
#                                                                                        #
######################################## 4BACKUP #########################################
#                                                                                        #
# <->mkstage4_gentoo: will create a stage 4 of your operating system                     #
#  |->                                                                                   #
#  usefull tool for backup and making your own linux repo stage4s                        #
#                                                                                        #
##########################################################################################
