#!/bin/bash

VERSION=0.0.1

#########################################################################################
#
# 4utoBl4ck 0.0.1 (4utoBl4ck)
#
# Idea / Written by Sebastian Vivian Gresser - All Rights Reserved
#
# Copyright (C) by geeBee UG (haftungsbeschränkt) - All Rights Reserved
# Copyright (C) by Sebastian Vivian Gresser - All Rights Reserved
#
#########################################################################################
#
# 4utoBl4ck: will blackhole any suspicious ips or domains in the domainlist
# with cron you can add this to auto-blackhole any network if you have their
# load balance domain names
#  |-> 4utoBl4ck needs Grsecurity's blackhole patch for ip route to work properly!!!
#
# examples for the domainlist domainlist=("example.com" "example.de")
#

domainlist=("")

for i in ${domainlist[@]}
do
	ip="$(ping -c 1 $i | sed -n -e 's/^PING.*(\(.*\))\ 56.*/\1/p')"
	echo $ip
	ip route add blackhole $ip
done

